### ISSUE TITLE
Performance on CityPersons

### ISSUE THREAD

**Issue by linchunze** [QihuaCheng/SNIP_Pedestrian-Detection#1]
Hello!
Can you report the performance of SNIP on Citypersons validation subset?
Which miss rate do you achieve on Reasonable and Heavy occlusion subsets?
Thanks in advance for you response.

**Comment by QihuaCheng** [comment]
| Reasonable  | Reasonable Small | Heavy occlusion | All |
| ------------- | ------------- | ------------- | ------------- |
| 10.5 | 13.2 | 47.6 | 38.9  |
